version: '3'
services: 
  apisix:
    image: tyltr_apisix:3.2LTS
    container_name: tyltr_apisix
    restart: always
    volumes:
      - ./docker_file/apisix/config-default.yaml:/usr/local/apisix/conf/config-default.yaml:ro
      - ./logs:/usr/local/apisix/logs:rw
    ports:
      - "9080:9080/tcp"
      - "9091:9091"