FROM openresty/openresty:1.21.4.1-alpine-fat
RUN set -x \
    && /bin/sed -i 's,http://dl-cdn.alpinelinux.org,https://mirrors.aliyun.com,g' /etc/apk/repositories \
    && apk add --no-cache --virtual .builddeps \
    automake \
    autoconf \
    libtool \
    pkgconfig \
    cmake \
    git \
    openldap-dev \
    sudo \
    && mkdir ~/.luarocks \
    && luarocks config variables.OPENSSL_LIBDIR /usr/local/openresty/openssl/lib \
    && luarocks config variables.OPENSSL_INCDIR /usr/local/openresty/openssl/include \
    && git config --global url.https://github.com/.insteadOf git://github.com/ \
    && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sudo sh -s -- -y \
    && source "$HOME/.cargo/env" \
    && export CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse \
    && export RUSTFLAGS="-C target-feature=-crt-static"  


WORKDIR /usr/local/apisix
COPY bin bin
COPY rockspec rockspec
RUN luarocks install rockspec/apisix-master-0.rockspec --tree=/usr/local/apisix/deps PCRE_DIR=/usr/local/openresty/pcre ]
COPY Makefile Makefile
COPY conf conf

ENV PATH=$PATH:/usr/local/openresty/luajit/bin:/usr/local/openresty/nginx/sbin:/usr/local/openresty/bin
# 代码
COPY apisix apisix

EXPOSE 9080  9091
CMD ["sh", "-c", "cd /usr/local/apisix && bin/apisix init && bin/apisix init_etcd && /usr/local/openresty/bin/openresty -p /usr/local/apisix -g 'daemon off;'"]
STOPSIGNAL SIGQUIT


# docker buildx build --platform linux/amd64,linux/arm64 -t tylitianrui/apisix_3.2lts:v2 --push .